---
title: "STAT 331 Project"
author: "Elizabeth Ellis, Barbara Ibrahim, Rhea Chellani"
format: html
editor: visual
---

```{r}
# Loading in libraries
library(tidyverse)
library(knitr)
library(readr)
```

```{r}
# Loading in data
gdp_data <- read.csv("gdp_pcap.csv")
life_expectancy_data <- read.csv("sp_dyn_le00_in.csv")
```

```{r}
# Pivoting GDP to long
gdp_long <- gdp_data |>
  select(country, X1960:X2022) |> 
  pivot_longer(cols = X1960:X2022,
               names_to = "Year",
               values_to = "GDP per Capita") |>
  mutate(
    Year = as.integer(str_remove(Year, "^X")),
    `GDP per Capita` = case_when(
      str_detect(`GDP per Capita`, "k") ~ parse_number(`GDP per Capita`) * 1000,
      TRUE ~ parse_number(`GDP per Capita`)))
# Only selecting 1960-2022 to match life expectancy and not include predicted GDP after 2022
```

```{r}
# Pivoting life expectancy to long
life_expectancy_long <- life_expectancy_data |>
  pivot_longer(cols = X1960:X2022, 
               names_to = "Year",
               values_to = "Life Expectancy") |>
  mutate(Year = as.integer(str_remove(Year, "^X")))
```

```{r}
# Joining life and gdp data
combined_data <- gdp_long |>
  inner_join(life_expectancy_long, join_by(country, Year))
```
